[package]
name = "veyra-cli"
description = "Inspectable command-line client for Veyra"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "veyra"
path = "src/main.rs"

[dependencies]
chrono.workspace = true
clap.workspace = true
futures-util.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio.workspace = true
url.workspace = true
veyra-protocol = { version = "0.1.0", path = "../veyra-protocol" }
veyra-server = { version = "0.1.0", path = "../veyra-server" }

[dev-dependencies]
assert_cmd = "2.1.1"
predicates = "3.1.4"

[lints]
workspace = true
